/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rana.view;

import Rana.Impl.SeatImpl;
import Rana.Model.SeatModel;
import Rana.util.DataBaseUtil;
import Rana.util.ResultsModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J2EE-27
 */
public class SeatPlan extends javax.swing.JFrame {
    DataBaseUtil dataBase;    
    SeatModel sm = new SeatModel();
    SeatImpl si = new SeatImpl();
//    Vector<String> colHead = new Vector<String>();
//    Vector<Vector<String>> rowData= new Vector<Vector<String>>(); 
//    DefaultTableModel model;
    ResultsModel rmodel = new ResultsModel();
    
    
    
    
    
    
    
    
    /**
     * Creates new form SeatPlan
     */
    public SeatPlan() {
        initComponents();
        try {
            dataBase = new DataBaseUtil();
            ResultSet rsbn = dataBase.getCon().createStatement().executeQuery("select * from schedule");
            while(rsbn.next()){
            cmbTBname.addItem(rsbn.getString(1));
            
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
           
            ResultSet tsl = dataBase.getCon().createStatement().executeQuery("Select * from seat");
            while(tsl.next()){
            //cmbtsl.addItem(tsl.getString(1));
            }

        } catch (SQLException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        
        tbldis.setModel(rmodel);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        btnA2 = new javax.swing.JButton();
        btnA1 = new javax.swing.JButton();
        btnA4 = new javax.swing.JButton();
        btnA3 = new javax.swing.JButton();
        btnB1 = new javax.swing.JButton();
        btnB2 = new javax.swing.JButton();
        btnB3 = new javax.swing.JButton();
        btnB4 = new javax.swing.JButton();
        btnC1 = new javax.swing.JButton();
        btnC2 = new javax.swing.JButton();
        btnC3 = new javax.swing.JButton();
        btnC4 = new javax.swing.JButton();
        btnD1 = new javax.swing.JButton();
        btnD2 = new javax.swing.JButton();
        btnD3 = new javax.swing.JButton();
        btnD4 = new javax.swing.JButton();
        btnE1 = new javax.swing.JButton();
        btnE2 = new javax.swing.JButton();
        btnE3 = new javax.swing.JButton();
        btnE4 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnF3 = new javax.swing.JButton();
        btnF4 = new javax.swing.JButton();
        btnG1 = new javax.swing.JButton();
        btnG2 = new javax.swing.JButton();
        btnG3 = new javax.swing.JButton();
        btnG4 = new javax.swing.JButton();
        btnH1 = new javax.swing.JButton();
        btnH2 = new javax.swing.JButton();
        btnH3 = new javax.swing.JButton();
        btnH4 = new javax.swing.JButton();
        btnI1 = new javax.swing.JButton();
        btnI2 = new javax.swing.JButton();
        btnI3 = new javax.swing.JButton();
        btnI4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtSl = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSeat = new javax.swing.JTextArea();
        cmbTBname = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbldis = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFare = new javax.swing.JTextField();
        rGeneral = new javax.swing.JRadioButton();
        rDeluxe = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        cmbTime = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        cmbDestination = new javax.swing.JComboBox();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnA2.setText("A2");
        btnA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA2ActionPerformed(evt);
            }
        });

        btnA1.setText("A1");
        btnA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA1ActionPerformed(evt);
            }
        });

        btnA4.setText("A4");
        btnA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA4ActionPerformed(evt);
            }
        });

        btnA3.setText("A3");
        btnA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnA3ActionPerformed(evt);
            }
        });

        btnB1.setText("B1");
        btnB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB1ActionPerformed(evt);
            }
        });

        btnB2.setText("B2");
        btnB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB2ActionPerformed(evt);
            }
        });

        btnB3.setText("B3");
        btnB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB3ActionPerformed(evt);
            }
        });

        btnB4.setText("B4");
        btnB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnB4ActionPerformed(evt);
            }
        });

        btnC1.setText("C1");
        btnC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC1ActionPerformed(evt);
            }
        });

        btnC2.setText("C2");
        btnC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC2ActionPerformed(evt);
            }
        });

        btnC3.setText("C3");
        btnC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC3ActionPerformed(evt);
            }
        });

        btnC4.setText("C4");
        btnC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnC4ActionPerformed(evt);
            }
        });

        btnD1.setText("D1");
        btnD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD1ActionPerformed(evt);
            }
        });

        btnD2.setText("D2");
        btnD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD2ActionPerformed(evt);
            }
        });

        btnD3.setText("D3");
        btnD3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD3ActionPerformed(evt);
            }
        });

        btnD4.setText("D4");
        btnD4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnD4ActionPerformed(evt);
            }
        });

        btnE1.setText("E1");
        btnE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE1ActionPerformed(evt);
            }
        });

        btnE2.setText("E2");
        btnE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE2ActionPerformed(evt);
            }
        });

        btnE3.setText("E3");
        btnE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE3ActionPerformed(evt);
            }
        });

        btnE4.setText("E4");
        btnE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnE4ActionPerformed(evt);
            }
        });

        btnF1.setText("F1");
        btnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF1ActionPerformed(evt);
            }
        });

        btnF2.setText("F2");
        btnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF2ActionPerformed(evt);
            }
        });

        btnF3.setText("F3");
        btnF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF3ActionPerformed(evt);
            }
        });

        btnF4.setText("F4");
        btnF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF4ActionPerformed(evt);
            }
        });

        btnG1.setText("G1");
        btnG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG1ActionPerformed(evt);
            }
        });

        btnG2.setText("G2");
        btnG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG2ActionPerformed(evt);
            }
        });

        btnG3.setText("G3");
        btnG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG3ActionPerformed(evt);
            }
        });

        btnG4.setText("G4");
        btnG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnG4ActionPerformed(evt);
            }
        });

        btnH1.setText("H1");
        btnH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH1ActionPerformed(evt);
            }
        });

        btnH2.setText("H2");
        btnH2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH2ActionPerformed(evt);
            }
        });

        btnH3.setText("H3");
        btnH3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH3ActionPerformed(evt);
            }
        });

        btnH4.setText("H4");
        btnH4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnH4ActionPerformed(evt);
            }
        });

        btnI1.setText("I1");
        btnI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI1ActionPerformed(evt);
            }
        });

        btnI2.setText("I2");
        btnI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI2ActionPerformed(evt);
            }
        });

        btnI3.setText("I3");
        btnI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI3ActionPerformed(evt);
            }
        });

        btnI4.setText("I4");
        btnI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnI4ActionPerformed(evt);
            }
        });

        jLabel1.setText("sl no");

        txtSl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSlActionPerformed(evt);
            }
        });
        txtSl.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSlFocusGained(evt);
            }
        });

        jLabel2.setText("Date");

        jLabel3.setText("Bus Name");

        txtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDateFocusGained(evt);
            }
        });

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("New");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel4.setText("Seat");

        txtSeat.setColumns(20);
        txtSeat.setRows(5);
        jScrollPane2.setViewportView(txtSeat);

        cmbTBname.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbTBnamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        tbldis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbldis);

        jLabel5.setText("Type");

        jLabel7.setText("Fare");

        buttonGroup1.add(rGeneral);
        rGeneral.setText("General");

        buttonGroup1.add(rDeluxe);
        rDeluxe.setText("Deluxe");
        rDeluxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rDeluxeActionPerformed(evt);
            }
        });

        jLabel8.setText("Time");

        cmbTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7am", "7pm" }));

        jLabel6.setText("Destination");

        cmbDestination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dhaka to Chittagong", "Dhaka to Coxsbazar", "Chittagong to Dhaka", "Coxsbazar to Dhaka" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(rGeneral)
                                .addGap(36, 36, 36)
                                .addComponent(rDeluxe))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(24, 24, 24)
                                .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(24, 24, 24)
                                .addComponent(cmbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnF4)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnF3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(148, 148, 148)
                                            .addComponent(btnF2)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnF1)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnB4)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(55, 55, 55)
                                                .addComponent(btnB3)
                                                .addGap(46, 46, 46)
                                                .addComponent(btnB2)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnB1)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnA4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnA3)
                                            .addGap(46, 46, 46)
                                            .addComponent(btnA2)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnA1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(146, 146, 146)
                                                .addComponent(btnC2)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnC1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnC4)
                                                .addGap(10, 10, 10)
                                                .addComponent(btnC3)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnD4)
                                                .addComponent(btnE4))
                                            .addGap(10, 10, 10)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnE3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnE2))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnD3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnD2)))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnE1)
                                                .addComponent(btnD1))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnG4)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnG3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(148, 148, 148)
                                            .addComponent(btnG2)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnG1))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnH4)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnH3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(146, 146, 146)
                                            .addComponent(btnH2)
                                            .addGap(20, 20, 20)
                                            .addComponent(btnH1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnI4)
                                        .addGap(22, 22, 22)
                                        .addComponent(btnI3)
                                        .addGap(42, 42, 42)
                                        .addComponent(btnI2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnI1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(btnSubmit)
                                .addGap(113, 113, 113)
                                .addComponent(btnClear))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbTBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtFare, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtSl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(rGeneral)
                            .addComponent(rDeluxe))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTBname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnA3)
                    .addComponent(btnA4)
                    .addComponent(btnA2)
                    .addComponent(btnA1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnB3)
                    .addComponent(btnB4)
                    .addComponent(btnB2)
                    .addComponent(btnB1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnC4)
                    .addComponent(btnC2)
                    .addComponent(btnC1)
                    .addComponent(btnC3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnD3)
                    .addComponent(btnD4)
                    .addComponent(btnD2)
                    .addComponent(btnD1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnE1)
                    .addComponent(btnE2)
                    .addComponent(btnE4)
                    .addComponent(btnE3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnF3)
                    .addComponent(btnF4)
                    .addComponent(btnF2)
                    .addComponent(btnF1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnG3)
                    .addComponent(btnG4)
                    .addComponent(btnG2)
                    .addComponent(btnG1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnH3)
                    .addComponent(btnH4)
                    .addComponent(btnH2)
                    .addComponent(btnH1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnI3)
                    .addComponent(btnI4)
                    .addComponent(btnI2)
                    .addComponent(btnI1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear)
                    .addComponent(btnSubmit))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA1ActionPerformed
        // TODO add your handling code here:
        String a1 ="A1 ";
       
        //txtSeat.append(a1);
        //txtsold.append(a1);
        
       
    }//GEN-LAST:event_btnA1ActionPerformed

    private void btnB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB1ActionPerformed
        // TODO add your handling code here:
         String b1 ="B1 ";
        //txtSeat.append(b1);
    }//GEN-LAST:event_btnB1ActionPerformed

    private void btnC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC1ActionPerformed
        // TODO add your handling code here:
        String c1 = "C1 ";
        //txtSeat.append(c1);
    }//GEN-LAST:event_btnC1ActionPerformed

    private void btnD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD1ActionPerformed
        // TODO add your handling code here:
        String d1 = "D1 ";
        txtSeat.append(d1);
        
    }//GEN-LAST:event_btnD1ActionPerformed

    private void btnE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE1ActionPerformed
        // TODO add your handling code here:
        String e1 = "E1 ";
        txtSeat.append(e1);
    }//GEN-LAST:event_btnE1ActionPerformed

    private void btnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF1ActionPerformed
        // TODO add your handling code here:
        String f1 = "F1 ";
        txtSeat.append(f1);
    }//GEN-LAST:event_btnF1ActionPerformed

    private void btnG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG1ActionPerformed
        // TODO add your handling code here:
        String g1 = "G1 ";
        txtSeat.append(g1);
    }//GEN-LAST:event_btnG1ActionPerformed

    private void btnH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH1ActionPerformed
        // TODO add your handling code here:
        String h1 = "H1 ";
        txtSeat.append(h1);
    }//GEN-LAST:event_btnH1ActionPerformed

    private void btnI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI1ActionPerformed
        // TODO add your handling code here:
        String i1 = "I1 ";
        txtSeat.append(i1);
    }//GEN-LAST:event_btnI1ActionPerformed

    public void sl(){
        int slNo = 1;
        try {
            ResultSet  rs =dataBase.getCon().createStatement().
                    executeQuery("Select max(slno) from seat");
            if(rs.next())
                slNo= rs.getInt(1)+1;
            txtSl.setText(slNo+"");
            
        
        
//            new Scania2seat(slNo+"");
          
            
        } catch (SQLException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    private void txtSlFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSlFocusGained
        // TODO add your handling code here:
        sl();
        
    }//GEN-LAST:event_txtSlFocusGained

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        sl();
        
        
        txtSeat.setText("");
        //txtsold.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    public void busname(String e1){
    //txtBusName.setText(e1);
    }
    private void txtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDateFocusGained
        // TODO add your handling code here:
        
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        txtDate.setText(dateFormat.format(date));
    }//GEN-LAST:event_txtDateFocusGained

    private void btnA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA2ActionPerformed
        // TODO add your handling code here:
        String a2 = "A2 ";
        txtSeat.append(a2);
        
    }//GEN-LAST:event_btnA2ActionPerformed

    private void btnA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA3ActionPerformed
        // TODO add your handling code here:
         String a3 = "A3 ";
        txtSeat.append(a3);
    }//GEN-LAST:event_btnA3ActionPerformed

    private void btnA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnA4ActionPerformed
        // TODO add your handling code here:
         String a4 = "A4 ";
        txtSeat.append(a4);
    }//GEN-LAST:event_btnA4ActionPerformed

    private void btnB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB2ActionPerformed
        // TODO add your handling code here:
        String b2 ="B2 ";
        txtSeat.append(b2);
        
    }//GEN-LAST:event_btnB2ActionPerformed

    private void btnB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB3ActionPerformed
        // TODO add your handling code here:
        String b3 = "B3 ";
        txtSeat.append(b3);
        
    }//GEN-LAST:event_btnB3ActionPerformed

    private void btnB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnB4ActionPerformed
        // TODO add your handling code here:
        String b4 = "B4 ";
        txtSeat.append(b4);
        
    }//GEN-LAST:event_btnB4ActionPerformed

    private void btnC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC2ActionPerformed
        // TODO add your handling code here:
        String c2 = "C2 ";
        txtSeat.append(c2);
        
    }//GEN-LAST:event_btnC2ActionPerformed

    private void btnC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC3ActionPerformed
        // TODO add your handling code here:
        String c3 = "C3 ";
        txtSeat.append(c3);
        
    }//GEN-LAST:event_btnC3ActionPerformed

    private void btnC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnC4ActionPerformed
        // TODO add your handling code here:
        String c4 = "C4 ";
        txtSeat.append(c4);
        
    }//GEN-LAST:event_btnC4ActionPerformed

    private void btnD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD2ActionPerformed
        // TODO add your handling code here:
        String d2 = "D2 ";
        txtSeat.append(d2);
    }//GEN-LAST:event_btnD2ActionPerformed

    private void btnD3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD3ActionPerformed
        // TODO add your handling code here:
        String d3 = "D3 ";
        txtSeat.append(d3);
    }//GEN-LAST:event_btnD3ActionPerformed

    private void btnD4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnD4ActionPerformed
        // TODO add your handling code here:
        String d4 = "D4 ";
        txtSeat.append(d4);
    }//GEN-LAST:event_btnD4ActionPerformed

    private void btnE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE2ActionPerformed
        // TODO add your handling code here:
        String e2 = "E2 ";
        txtSeat.append(e2);
        
    }//GEN-LAST:event_btnE2ActionPerformed

    private void btnE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE3ActionPerformed
        // TODO add your handling code here:
        String e3 = "E3 ";
        txtSeat.append(e3);
        
    }//GEN-LAST:event_btnE3ActionPerformed

    private void btnE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnE4ActionPerformed
        // TODO add your handling code here:
        String e4 = "E4 ";
        txtSeat.append(e4);
    }//GEN-LAST:event_btnE4ActionPerformed

    private void btnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF2ActionPerformed
        // TODO add your handling code here:
        String f2 = "F2 ";
        txtSeat.append(f2);
    }//GEN-LAST:event_btnF2ActionPerformed

    private void btnF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF3ActionPerformed
        // TODO add your handling code here:
        String f3 = "F3 ";
        txtSeat.append(f3);
    }//GEN-LAST:event_btnF3ActionPerformed

    private void btnF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF4ActionPerformed
        // TODO add your handling code here:
        String f4 = "F4 ";
        txtSeat.append(f4);
    }//GEN-LAST:event_btnF4ActionPerformed

    private void btnG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG2ActionPerformed
        // TODO add your handling code here:
        String g2 = "G2 ";
        txtSeat.append(g2);
    }//GEN-LAST:event_btnG2ActionPerformed

    private void btnG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG3ActionPerformed
        // TODO add your handling code here:
        String g3 = "G3 ";
        txtSeat.append(g3);
    }//GEN-LAST:event_btnG3ActionPerformed

    private void btnG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnG4ActionPerformed
        // TODO add your handling code here:
        String g4 = "G4 ";
        txtSeat.append(g4);
    }//GEN-LAST:event_btnG4ActionPerformed

    private void btnH2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH2ActionPerformed
        // TODO add your handling code here:
        String h2 = "H2 ";
        txtSeat.append(h2);
    }//GEN-LAST:event_btnH2ActionPerformed

    private void btnH3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH3ActionPerformed
        // TODO add your handling code here:
        String h3 = "H3 ";
        txtSeat.append(h3);
    }//GEN-LAST:event_btnH3ActionPerformed

    private void btnH4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnH4ActionPerformed
        // TODO add your handling code here:
        String h4 = "H4 ";
        txtSeat.append(h4);
    }//GEN-LAST:event_btnH4ActionPerformed

    private void btnI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI2ActionPerformed
        // TODO add your handling code here:
        String i2= "I2 ";
        txtSeat.append(i2);
    }//GEN-LAST:event_btnI2ActionPerformed

    private void btnI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI3ActionPerformed
        // TODO add your handling code here:
        String i3 = "I3 ";
        txtSeat.append(i3);
    }//GEN-LAST:event_btnI3ActionPerformed

    private void btnI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnI4ActionPerformed
        // TODO add your handling code here:
        String i4 = "I4 " ;
        txtSeat.append(i4);
    }//GEN-LAST:event_btnI4ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
       
        sm.setSlno(Integer.parseInt(txtSl.getText()));
        sm.setDate(txtDate.getText().trim());
        sm.setSeat(txtSeat.getText().trim());
        sm.setBusname(cmbTBname.getSelectedItem().toString());
        sm.setType(rDeluxe.isSelected()?"Deluxe":"General");
        sm.setTime(cmbTime.getSelectedItem().toString());
        sm.setDestination(cmbDestination.getSelectedItem().toString());
        sm.setFare(Double.parseDouble(txtFare.getText().trim()));
        
        si.save(sm);
        
        int bname = cmbTBname.getSelectedIndex();
        if(bname==0){
         String sql = "insert into econo1 values(?,?,?,?,?,?,?,?)";
            try {
                PreparedStatement pstm = dataBase.getCon().prepareStatement(sql);
                pstm.setString(1, txtSl.getText());
                pstm.setString(2, txtDate.getText());
                pstm.setString(3, txtSeat.getText());
                pstm.setString(4, cmbTBname.getSelectedItem().toString());
                pstm.setString(5, rDeluxe.isSelected()?"Deluxe":"General");
                pstm.setString(6, cmbTime.getSelectedItem().toString());
                pstm.setString(7, cmbDestination.getSelectedItem().toString());
                pstm.setDouble(8, Double.parseDouble(txtFare.getText()));
                
                
                
                pstm.executeUpdate();
                pstm.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    
    public void g(){
        
           try {
             
            ResultSet general = dataBase.getCon().createStatement().executeQuery("Select * from schedule where busname =");
            while(general.next()){
            txtFare.setText(general.getString(6));
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
           
           
        };
    private void cmbTBnamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbTBnamePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        
            String d = txtDate.getText();
            String bn= cmbTBname.getSelectedItem().toString().trim();
            int bnm = cmbTBname.getSelectedIndex();
            String sql="Select * from schedule where BusName='"+bn+"'";
            System.out.println(" ......"+sql);
             try {
             
            ResultSet general = dataBase.getCon().createStatement().executeQuery(sql);
            if(general.next()){
            
                txtFare.setText(general.getString("Fare"));
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            if(bnm==0){
            
                try {
                ResultSet rs0 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'econo1' ");
               rmodel.setResultSet(rs0);
               
                        
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(bnm==1){
            
                try {
                ResultSet rs1 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'econo2'  ");
               rmodel.setResultSet(rs1);
                    
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(bnm == 2){
            
            try {
                ResultSet rs2 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'econo3'  ");
               rmodel.setResultSet(rs2);
              
                        
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(bnm == 3){
            
            try {
                ResultSet rs3 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'econo4'  ");
               rmodel.setResultSet(rs3);
               
                        
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if( bnm == 4){
            
            try {
                ResultSet rs4 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'scania1' ");
               rmodel.setResultSet(rs4);
                      
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(bnm==5){
            try {
                ResultSet rs5 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'scania2'  ");
               rmodel.setResultSet(rs5);
      
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if(bnm == 6){
            
            try {
                ResultSet rs6 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'scania3'  ");
               rmodel.setResultSet(rs6);
     
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }else if( bnm == 7){
            
            try {
                ResultSet rs7 = dataBase.getCon().createStatement().executeQuery("select * from seat where busname= 'scania4' ");
               rmodel.setResultSet(rs7);
  
                        
                        } catch (SQLException ex) {
                Logger.getLogger(SeatPlan.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            
    }//GEN-LAST:event_cmbTBnamePopupMenuWillBecomeInvisible

    private void txtSlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSlActionPerformed

    private void rDeluxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rDeluxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rDeluxeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeatPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeatPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA1;
    private javax.swing.JButton btnA2;
    private javax.swing.JButton btnA3;
    private javax.swing.JButton btnA4;
    private javax.swing.JButton btnB1;
    private javax.swing.JButton btnB2;
    private javax.swing.JButton btnB3;
    private javax.swing.JButton btnB4;
    private javax.swing.JButton btnC1;
    private javax.swing.JButton btnC2;
    private javax.swing.JButton btnC3;
    private javax.swing.JButton btnC4;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnD1;
    private javax.swing.JButton btnD2;
    private javax.swing.JButton btnD3;
    private javax.swing.JButton btnD4;
    private javax.swing.JButton btnE1;
    private javax.swing.JButton btnE2;
    private javax.swing.JButton btnE3;
    private javax.swing.JButton btnE4;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnF2;
    private javax.swing.JButton btnF3;
    private javax.swing.JButton btnF4;
    private javax.swing.JButton btnG1;
    private javax.swing.JButton btnG2;
    private javax.swing.JButton btnG3;
    private javax.swing.JButton btnG4;
    private javax.swing.JButton btnH1;
    private javax.swing.JButton btnH2;
    private javax.swing.JButton btnH3;
    private javax.swing.JButton btnH4;
    private javax.swing.JButton btnI1;
    private javax.swing.JButton btnI2;
    private javax.swing.JButton btnI3;
    private javax.swing.JButton btnI4;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbDestination;
    private javax.swing.JComboBox<String> cmbTBname;
    private javax.swing.JComboBox cmbTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rDeluxe;
    private javax.swing.JRadioButton rGeneral;
    private javax.swing.JTable tbldis;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtFare;
    private javax.swing.JTextArea txtSeat;
    private javax.swing.JTextField txtSl;
    // End of variables declaration//GEN-END:variables

    
}
